<html>
  <head>
    <title>Is <?php echo $alias ? $alias : $username?> Dead Yet?</title>
    <link href='http://fonts.googleapis.com/css?family=Raleway:400,100' rel='stylesheet' type='text/css'>
    <link rel="stylesheet" type="text/css" href="style.css" />
  </head>
  <body>
    <div class="tagline"><?php echo $tagline?></div>
    <div class="deadyet" title="Last seen at <?php echo date('Y-m-d H:i:s',$last_time_seen); ?>"><?php echo $state; ?>. <?php echo $adjective?>.</div>
  </body>
</html>
